apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: minio-gateway-standard-system

resources:
  - ../../base/

commonLabels:
  data.statcan.gc.ca/classification: protected-b

#patchesStrategicMerge:
#- cluster-role.yaml
#- deployment.yaml
#- deployment_patch.yaml

configMapGenerator:
- files:
  - policy.rego
  name: minio-gateway-opa
