apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aad-refresher-rb
subjects:
  - kind: ServiceAccount
    name: aad-refresher-sa
roleRef:
  kind: Role
  name: aad-refresher-role
  apiGroup: rbac.authorization.k8s.io
