apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJson6902:
- target:
    version: v1
    kind: (Deployment|StatefulSet)
    name: minio-gateway.*
  patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector/agentpool"
      value: storage
    - op: add
      path: "/spec/template/spec/tolerations/-"
      value:
        effect: NoSchedule
        key: node.statcan.gc.ca/purpose
        operator: Equal
        value: system
    - op: add
      path: "/spec/template/spec/tolerations/-"
      value:
        effect: NoSchedule
        key: node.statcan.gc.ca/use
        operator: Equal
        value: storage
