apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: minio-gateway-standard-ro-system

resources:
  - ../../base/

configMapGenerator:
- files:
  - policy.rego
  name: minio-gateway-opa
