nameOverride: "minio-gateway"
commonLabels:
  app: minio-gateway
auth:
  existingSecret: minio-gateway-secret
gateway:
  enabled: true
  replicaCount: 1
  type: s3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  # autoscaling:
  #   enabled: true
  #   minReplicas: "2"
  #   maxReplicas: "4"
  #   targetCPU: "60"
  #   targetMemory: "60"
  auth:
    existingSecret: minio-gateway-secret
    s3:
      accessKey: "minioadmin"
      secretKey: "minioadmin"
      serviceEndpoint: https://happylittlecloud-minio.nyc3.digitaloceanspaces.com
extraEnvVars:
  - name: MINIO_ETCD_ENDPOINTS
    value: http://minio-gateway-etcd:2379/
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: spaces-secret
        key: accessKey
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: spaces-secret
        key: secretKey

  #- name: MINIO_IAM_OPA_URL
  #  value: http://minio-gateway-opa:8181/v1/data/httpapi/authz
ingress:
  enabled: false
resources: {}
tolerations: []
