apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-gateway-etcd
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/charts
    targetRevision: 6.13.2
    chart: etcd
    helm:
      values: |
         nameOverride: "minio-gateway"
         commonLabels:
           app: minio-gateway-etcd
         auth:
           token:
             type: simple
           rbac:
             create: false
             enabled: false
         replicaCount: 3
         initialClusterState: new
         persistence:
           enabled: false
         resources: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
