nameOverride: "minio-gateway"
commonLabels:
  app: minio-gateway-etcd
auth:
  rbac:
    enabled: false
image:
  # registry: docker.io
  # repository: bitnami/etcd
  # tag: 3.5.0-debian-10-r64
  registry: k8scc01covidacr.azurecr.io
  repository: etcd
  tag: 3.5.0-debian-10-r64
replicaCount: 1
persistence:
  enabled: false
resources:
  limits:
    cpu: "2"
    memory: 8Gi
  requests:
    cpu: "2"
    memory: 8Gi
# nodeSelector:
#   agentpool: storage
# affinity:
#   podAntiAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - podAffinityTerm:
#         labelSelector:
#           matchExpressions:
#           - key: app
#             operator: In
#             values:
#             - minio-gateway-etcd
#         topologyKey: kubernetes.io/hostname
#       weight: 100
# - effect: NoSchedule
#   key: node.statcan.gc.ca/purpose
#   operator: Equal
#   value: system
# - effect: NoSchedule
#   key: node.statcan.gc.ca/use
#   operator: Equal
#   value: storage
# # - effect: NoSchedule
# #   key: data.statcan.gc.ca/classification
# #   operator: Equal
# #   value: protected-b

